export interface DocumentationGuide {
  readonly slug: string;
  readonly title: string;
  readonly summary: string;
  readonly topics: readonly string[];
  readonly content: string;
}

function markdown(lines: readonly string[]): string {
  return lines.join("\n");
}

export const documentationGuides: readonly DocumentationGuide[] = [
  {
    slug: "getting-started",
    title: "Getting started",
    summary: "Install Brilliant UI, load its Tailwind stylesheet, and render the first component.",
    topics: ["installation", "tailwind", "imports", "mcp"],
    content: markdown([
      "# Getting started",
      "",
      "Brilliant UI requires React 19.1 or newer, Tailwind CSS v4, and Node.js 20 or newer for tooling.",
      "",
      "## Install",
      "",
      "```bash",
      "pnpm add @brilliantmode/ui tailwindcss",
      "```",
      "",
      "## Load the global stylesheet",
      "",
      "Add these imports once in the application's global CSS file:",
      "",
      "```css",
      '@import "tailwindcss";',
      '@import "@brilliantmode/ui/styles.css";',
      "```",
      "",
      "## Import a component",
      "",
      "Use component subpaths so bundlers include only what the application imports:",
      "",
      "```tsx",
      'import { Button } from "@brilliantmode/ui/button";',
      "",
      "export function SaveButton() {",
      "  return <Button>Save changes</Button>;",
      "}",
      "```",
      "",
      "For AI-authored interfaces, search the catalog first and retrieve each selected component before writing code. The component result contains the exact import, API declaration, accessibility notes, and a version-matched example.",
    ]),
  },
  {
    slug: "theming",
    title: "Theming and design tokens",
    summary:
      "Brand an application through semantic CSS variables and version-matched token groups.",
    topics: ["theming", "tokens", "css", "dark-mode", "branding"],
    content: markdown([
      "# Theming and design tokens",
      "",
      "Brilliant UI components consume semantic Tailwind classes such as `bg-primary`, `text-primary-foreground`, `border-border`, and `ring-ring`. Customize the semantic variables instead of editing every component.",
      "",
      "Override variables after importing the Brilliant stylesheet:",
      "",
      "```css",
      ":root {",
      "  --brilliant-primary: oklch(0.54 0.23 276);",
      "  --brilliant-ring: oklch(0.61 0.22 276);",
      "  --brilliant-radius: 0.625rem;",
      "}",
      "```",
      "",
      "Use `get_design_tokens` before generating token-dependent code. Available groups cover semantic and primitive colors, spacing, typography, radii, elevation, density, motion, opacity, border width, breakpoints, and z-index.",
      "",
      "Keep product colors semantic. Do not replace component classes with hard-coded palette values, and preserve sufficient contrast in every appearance.",
    ]),
  },
  {
    slug: "component-composition",
    title: "Component composition",
    summary:
      "Choose primitives, layouts, and blocks without inventing unsupported Brilliant UI APIs.",
    topics: ["components", "composition", "layouts", "blocks", "imports"],
    content: markdown([
      "# Component composition",
      "",
      "Use `search_components` for known concepts and `suggest_components` for an interface description. Then call `get_component` for every chosen item before implementing it.",
      "",
      "Prefer the smallest appropriate layer:",
      "",
      "- Components are focused controls and surfaces such as Button, Field, Dialog, Table, and Tabs.",
      "- Layouts provide page structure such as Application Shell and Dashboard Layout.",
      "- Blocks combine primitives for a specific workflow, such as Analytics Overview Dashboard or Onboarding Wizard.",
      "",
      "Import each item from the exact subpath returned by the MCP. Do not infer props from another design system, and do not import internal generated files.",
      "",
      "Keep one primary action per region, use semantic HTML around the components, and preserve the component's documented slots and interaction states when composing larger interfaces.",
    ]),
  },
  {
    slug: "forms-and-validation",
    title: "Forms and validation",
    summary:
      "Compose labeled, accessible form controls with clear help, error, and submission states.",
    topics: ["forms", "validation", "input", "field", "accessibility"],
    content: markdown([
      "# Forms and validation",
      "",
      "Build forms from native-first Brilliant controls such as Field, Label, Input, Textarea, Select, Checkbox, Switch, Radio Group, Slider, Date Input, File Upload, and Photo Upload.",
      "",
      "For each field:",
      "",
      "- Provide a visible label and stable control identifier.",
      "- Connect help and error text with the appropriate ARIA description attributes.",
      "- Set native invalid and disabled state as well as visual state.",
      "- Keep validation messages specific and place them next to the affected field.",
      "- Preserve entered values after a failed submission.",
      "",
      "Use Button for submission actions and expose loading without removing the action label. Retrieve every form component before coding because exact props and composition differ by primitive.",
    ]),
  },
  {
    slug: "overlays-and-feedback",
    title: "Overlays and feedback",
    summary:
      "Select dialogs, drawers, menus, hints, alerts, and transient feedback by interaction risk.",
    topics: ["dialog", "drawer", "menu", "tooltip", "toast", "feedback"],
    content: markdown([
      "# Overlays and feedback",
      "",
      "Choose the surface according to the interaction:",
      "",
      "- Dialog: focused modal work with a clear completion or dismissal path.",
      "- Alert Dialog: destructive or high-risk confirmation.",
      "- Drawer or Sheet: secondary workflows, filters, and settings.",
      "- Dropdown Menu or Context Menu: compact secondary actions.",
      "- Popover or Hover Card: contextual content that does not require a full modal.",
      "- Tooltip: a short hint, never essential instructions.",
      "- Alert: persistent status or guidance; Toast: transient confirmation.",
      "",
      "Do not nest modal surfaces. Keep destructive actions explicit, return focus when an overlay closes, and ensure every icon-only trigger has an accessible name. Retrieve the selected component for its exact structure and keyboard behavior.",
    ]),
  },
  {
    slug: "accessibility-and-motion",
    title: "Accessibility and motion",
    summary:
      "Preserve native semantics, keyboard operation, visible focus, and reduced-motion behavior.",
    topics: ["accessibility", "keyboard", "focus", "motion", "aria"],
    content: markdown([
      "# Accessibility and motion",
      "",
      "Treat the accessibility array returned by `get_component` as implementation requirements, not optional suggestions.",
      "",
      "General rules:",
      "",
      "- Prefer native controls and landmarks whenever they express the interaction.",
      "- Preserve visible focus and logical keyboard order.",
      "- Give icon-only controls an accessible name.",
      "- Associate labels, descriptions, validation messages, and status updates programmatically.",
      "- Do not communicate state through color alone.",
      "- Preserve `motion-safe` and `motion-reduce` behavior in motion-bearing components.",
      "",
      "When composing multiple primitives, test keyboard entry, operation, dismissal, focus restoration, screen-reader naming, zoom, contrast, and reduced-motion preferences.",
    ]),
  },
  {
    slug: "dashboards-and-data",
    title: "Dashboards and data display",
    summary:
      "Compose readable enterprise dashboards from metrics, status, charts, tables, and layouts.",
    topics: ["dashboard", "chart", "table", "metrics", "status", "responsive"],
    content: markdown([
      "# Dashboards and data display",
      "",
      "Use Dashboard Layout or Application Shell for structure, then compose Stat, Status, Meter, Chart, Table, Progress, and Empty State according to the data's meaning.",
      "",
      "Keep the hierarchy restrained:",
      "",
      "- Put the decision-driving metric first.",
      "- Pair trends with a time window and comparison basis.",
      "- Label chart series and units; do not rely on color alone.",
      "- Use tables when exact comparison matters and charts when shape or trend matters.",
      "- Provide loading, empty, error, and stale-data states.",
      "- Keep dense controls keyboard reachable and usable at narrow widths.",
      "",
      "Start from a dashboard block only when its workflow matches the request. Otherwise compose primitives and retrieve each API before implementation.",
    ]),
  },
  {
    slug: "troubleshooting-and-upgrades",
    title: "Troubleshooting and upgrades",
    summary: "Diagnose missing styles, import failures, MCP startup issues, and package upgrades.",
    topics: ["troubleshooting", "upgrade", "mcp", "styles", "imports"],
    content: markdown([
      "# Troubleshooting and upgrades",
      "",
      "## Components render without Brilliant styling",
      "",
      "Confirm the global stylesheet imports Tailwind first and `@brilliantmode/ui/styles.css` second. Ensure the CSS file is loaded by the application entry point.",
      "",
      "## A component import fails",
      "",
      "Use the exact `importPath` returned by `get_component`. Do not guess a barrel export or import from `dist` or `src` internals.",
      "",
      "## The MCP process exits or exposes no tools",
      "",
      "Run the MCP command from a project where `@brilliantmode/ui` is installed. The client must launch `pnpm exec brilliant-ui-mcp` over stdio; the command is expected to remain silent while waiting for protocol messages. Restart the MCP connection after changing its configuration or upgrading the package.",
      "",
      "## Upgrade",
      "",
      "Run `pnpm up @brilliantmode/ui`, review release notes, restart the MCP connection, and retrieve component documentation again so generated code matches the installed version.",
    ]),
  },
] as const;
