/* Generated from the Brilliant UI registry. Do not edit directly. */
export const packageVersion = "0.1.0";
export const componentCatalog = [
  {
    dependencies: [],
    description: "An accessible action control with semantic visual hierarchy.",
    exports: ["ButtonProps", "Button"],
    importPath: "@brilliant/ui/button",
    kind: "component",
    metadata: {
      purpose: "Triggers an immediate action or submits a form.",
      slots: ["root", "icon", "label"],
      accessibility: [
        "Uses a native button element.",
        "Icon-only buttons require an aria-label.",
        "Focus is always visible for keyboard users.",
        "Motion is guarded by motion-safe and motion-reduce variants.",
      ],
      usage: [
        "Use a single primary action per region.",
        "Prefer verbs for labels.",
        "Micro interactions are included in the generated source.",
      ],
      avoid: ["Do not use for navigation; use a link.", "Do not disable without explaining why."],
    },
    name: "button",
    registryDependencies: [],
    title: "Button",
    valueExports: ["Button"],
  },
  {
    dependencies: [],
    description: "A grouped action wrapper for related Brilliant buttons.",
    exports: ["ButtonGroupProps", "ButtonGroup"],
    importPath: "@brilliant/ui/button-group",
    kind: "component",
    metadata: {
      purpose: "Groups related actions into one compact control cluster.",
      slots: ["root", "button"],
      accessibility: [
        "Uses role group.",
        "Add aria-label or aria-labelledby when the grouped actions need a name.",
        "Keeps child button focus rings above adjacent controls.",
      ],
      usage: [
        "Use for related actions of the same scope.",
        "Keep groups small, usually two to four actions.",
        "Use vertical orientation only in constrained side panels.",
      ],
      avoid: ["Do not group unrelated primary actions."],
    },
    name: "button-group",
    registryDependencies: ["button"],
    title: "Button Group",
    valueExports: ["ButtonGroup"],
  },
  {
    dependencies: [],
    description: "A compact status label for metadata, state, and categorization.",
    exports: ["BadgeProps", "Badge"],
    importPath: "@brilliant/ui/badge",
    kind: "component",
    metadata: {
      purpose: "Labels objects with short status or category text.",
      slots: ["root", "label"],
      accessibility: ["Uses readable text by default.", "Avoid color-only meaning."],
      usage: ["Use one or two words.", "Pair semantic color with clear copy."],
      avoid: ["Do not use for primary actions.", "Do not use long sentences."],
    },
    name: "badge",
    registryDependencies: [],
    title: "Badge",
    valueExports: ["Badge"],
  },
  {
    dependencies: [],
    description: "A ratio-preserving media wrapper for previews, thumbnails, and embeds.",
    exports: ["AspectRatioProps", "AspectRatio"],
    importPath: "@brilliant/ui/aspect-ratio",
    kind: "component",
    metadata: {
      purpose: "Keeps media and preview surfaces at a predictable aspect ratio.",
      slots: ["root", "content"],
      accessibility: [
        "Preserves the semantics of children.",
        "Images and embeds inside still need their own accessible names.",
      ],
      usage: [
        "Use ratio={16 / 9} for previews and video.",
        "Use ratio={1} for square thumbnails.",
        "Put images, iframes, or preview surfaces inside the wrapper.",
      ],
      avoid: ["Do not crop meaningful content without an alternate way to access it."],
    },
    name: "aspect-ratio",
    registryDependencies: [],
    title: "Aspect Ratio",
    valueExports: ["AspectRatio"],
  },
  {
    dependencies: [],
    description: "A tokenized image primitive with ratio, fallback, caption, and reveal micro UX.",
    exports: [
      "PhotoProps",
      "Photo",
      "PhotoImageProps",
      "PhotoImage",
      "PhotoTintProps",
      "PhotoTint",
      "PhotoFallbackProps",
      "PhotoFallback",
      "PhotoCaption",
    ],
    importPath: "@brilliant/ui/photo",
    kind: "component",
    metadata: {
      purpose: "Renders product imagery, thumbnails, avatars-at-scale, and media previews.",
      slots: ["root", "image", "tint", "fallback", "caption"],
      accessibility: [
        "PhotoImage requires meaningful alt text unless the image is decorative.",
        "PhotoFallback remains visible when the image fails to load.",
        "PhotoCaption uses figcaption semantics through the parent figure.",
      ],
      usage: [
        "Use ratio to reserve space and prevent layout shift.",
        "Use crop square or circle for fixed 1:1 crops; circle overrides radius.",
        "Use PhotoImage filter presets for repeatable image treatment.",
        "Use PhotoTint for tokenized or custom color overlays.",
        "Use variant surface for ordinary media cards.",
        "Use radius to align image corners with surrounding surfaces.",
        "Use PhotoCaption only when the caption describes the image, not as decoration.",
      ],
      avoid: [
        "Do not use background images for meaningful content.",
        "Do not omit alt text for informative images.",
        "Do not crop important product details without a fallback view.",
      ],
    },
    name: "photo",
    registryDependencies: [],
    title: "Photo",
    valueExports: ["Photo", "PhotoImage", "PhotoTint", "PhotoFallback", "PhotoCaption"],
  },
  {
    dependencies: [],
    description: "A user/object avatar with image fallback, size presets, and status presence.",
    exports: [
      "AvatarProps",
      "Avatar",
      "AvatarImageProps",
      "AvatarImage",
      "AvatarFallbackProps",
      "AvatarFallback",
      "AvatarStatusProps",
      "AvatarStatus",
    ],
    importPath: "@brilliant/ui/avatar",
    kind: "component",
    metadata: {
      purpose: "Represents a person, team, workspace, or object identity.",
      slots: ["root", "image", "fallback", "status"],
      accessibility: [
        "Use meaningful alt text for profile images or empty alt for decorative avatars.",
        "Fallback text remains visible when the image fails.",
        "Status exposes a short status label.",
      ],
      usage: [
        "Use initials as fallback for people and short labels for workspaces.",
        "Use status only when presence is meaningful.",
        "Keep avatar sizes consistent inside dense lists.",
      ],
      avoid: ["Do not rely on color alone to identify a person or state."],
    },
    name: "avatar",
    registryDependencies: [],
    title: "Avatar",
    valueExports: ["Avatar", "AvatarImage", "AvatarFallback", "AvatarStatus"],
  },
  {
    dependencies: [],
    description: "A calm content container with variants and optional hover/press micro UX.",
    exports: [
      "CardProps",
      "Card",
      "CardHeader",
      "CardTitle",
      "CardDescription",
      "CardContent",
      "CardFooter",
    ],
    importPath: "@brilliant/ui/card",
    kind: "component",
    metadata: {
      purpose: "Groups related UI into a scannable surface.",
      slots: ["root", "header", "title", "description", "content", "footer"],
      accessibility: [
        "Preserves semantic children.",
        "Headings remain author-controlled.",
        "Interactive cards still need a real link or button for navigation/actions.",
      ],
      usage: [
        "Use surface for ordinary groups.",
        "Use elevated for raised dashboard summaries.",
        "Use accent for selected or highlighted information.",
        "Use beam for premium live, AI, processing, or highlighted states.",
        "Set beam from app state for live processing states, for example beam={isProcessing}.",
        "Set interactive when the card represents a clickable target.",
      ],
      avoid: ["Do not nest too many cards.", "Do not use cards as random decoration."],
    },
    name: "card",
    registryDependencies: [],
    title: "Card",
    valueExports: [
      "Card",
      "CardHeader",
      "CardTitle",
      "CardDescription",
      "CardContent",
      "CardFooter",
    ],
  },
  {
    dependencies: [],
    description: "A typography primitive with muted, glow, and shimmer variants.",
    exports: ["TextProps", "Text"],
    importPath: "@brilliant/ui/text",
    kind: "component",
    metadata: {
      purpose: "Renders short UI copy, premium states, and animated emphasis text.",
      slots: ["root", "content"],
      accessibility: [
        "Renders real text, not an image.",
        "Shimmer animation is disabled for reduced-motion users.",
        "Use semantic elements through the as prop when needed.",
      ],
      usage: [
        "Use default or muted for ordinary copy.",
        "Use glow for premium status labels and AI states.",
        "Use shimmer for short loading, generating, or live processing text.",
        "Override shimmerColor per use, or set --brilliant-text-shimmer-highlight globally.",
        "Keep animated text short and meaningful.",
      ],
      avoid: [
        "Do not use shimmer for paragraphs.",
        "Do not rely on animation alone to communicate state.",
      ],
    },
    name: "text",
    registryDependencies: [],
    title: "Text",
    valueExports: ["Text"],
  },
  {
    dependencies: [],
    description: "A crisp text field with focus, invalid, disabled, and tokenized styling.",
    exports: ["InputProps", "Input"],
    importPath: "@brilliant/ui/input",
    kind: "component",
    metadata: {
      purpose: "Collects short freeform text, search, numbers, URLs, or emails.",
      slots: ["root"],
      accessibility: ["Pair with a label.", "Supports aria-invalid for error state."],
      usage: [
        "Use type-specific inputs where possible.",
        "Include helpful placeholder text sparingly.",
      ],
      avoid: ["Do not rely on placeholder as the only label."],
    },
    name: "input",
    registryDependencies: [],
    title: "Input",
    valueExports: ["Input"],
  },
  {
    dependencies: [],
    description:
      "A functional file picker and dropzone with validation, removable files, and upload progress UI.",
    exports: [
      "FileUploadProps",
      "FileUpload",
      "FileUploadDropzone",
      "FileUploadIcon",
      "FileUploadTitle",
      "FileUploadDescription",
      "FileUploadTrigger",
      "FileUploadList",
      "FileUploadError",
    ],
    importPath: "@brilliant/ui/file-upload",
    kind: "component",
    metadata: {
      purpose: "Collects one or more local files before an application uploads or processes them.",
      slots: [
        "root",
        "input",
        "dropzone",
        "icon",
        "title",
        "description",
        "trigger",
        "list",
        "item",
        "progress",
        "error",
      ],
      accessibility: [
        "Uses a native file input as the source of truth.",
        "The dropzone is a keyboard-operable button with visible focus.",
        "Validation messages use role alert.",
        "Progress uses native progressbar semantics and remove controls have file-specific labels.",
      ],
      usage: [
        "Use accept, maxSize, and maxFiles to validate selection before upload.",
        "Use multiple when more than one file is allowed.",
        "Use onFilesChange to connect the selected File objects to application upload logic.",
        "Pass progress keyed by file name when upload progress is available.",
      ],
      avoid: [
        "Do not imply that selecting a file uploads it automatically.",
        "Do not rely on the accept attribute as server-side validation.",
        "Do not remove selected files without an explicit user action.",
      ],
    },
    name: "file-upload",
    registryDependencies: [],
    title: "File Upload",
    valueExports: [
      "FileUpload",
      "FileUploadDropzone",
      "FileUploadIcon",
      "FileUploadTitle",
      "FileUploadDescription",
      "FileUploadTrigger",
      "FileUploadList",
      "FileUploadError",
    ],
  },
  {
    dependencies: [],
    description:
      "An image-specific upload with immediate preview, crop controls, replace and remove actions, and optional camera capture.",
    exports: ["PhotoUploadProps", "PhotoUpload"],
    importPath: "@brilliant/ui/photo-upload",
    kind: "component",
    metadata: {
      purpose:
        "Selects and previews a profile, workspace, product, or content image before upload.",
      slots: ["root", "dropzone", "preview", "image", "actions", "progress", "error"],
      accessibility: [
        "Uses the native file input provided by File Upload.",
        "Replace and remove actions are keyboard operable with visible focus.",
        "The preview requires meaningful alt text and upload progress uses progressbar semantics.",
      ],
      usage: [
        "Use crop rectangle, square, or circle to match the final image treatment.",
        "Pass src to preview an existing image before a replacement is selected.",
        "Use file and onFileChange for controlled upload flows.",
        "Use capture user or environment to offer camera capture on supported mobile devices.",
      ],
      avoid: [
        "Do not imply that selecting a photo uploads it automatically.",
        "Do not skip server-side file validation and image processing.",
        "Do not use a circle crop when the saved asset is not an avatar or logo.",
      ],
    },
    name: "photo-upload",
    registryDependencies: ["file-upload", "photo"],
    title: "Photo Upload",
    valueExports: ["PhotoUpload"],
  },
  {
    dependencies: [],
    description: "A form label primitive tuned for dense enterprise layouts.",
    exports: ["LabelProps", "Label"],
    importPath: "@brilliant/ui/label",
    kind: "component",
    metadata: {
      purpose: "Names a form control.",
      slots: ["root"],
      accessibility: ["Use htmlFor to connect labels to controls."],
      usage: ["Keep labels concise.", "Use helper text for extra instructions."],
      avoid: ["Do not replace labels with placeholders."],
    },
    name: "label",
    registryDependencies: [],
    title: "Label",
    valueExports: ["Label"],
  },
  {
    dependencies: [],
    description: "A multiline field with Brilliant focus and invalid states.",
    exports: ["TextareaProps", "Textarea"],
    importPath: "@brilliant/ui/textarea",
    kind: "component",
    metadata: {
      purpose: "Collects longer freeform text.",
      slots: ["root"],
      accessibility: ["Pair with a label.", "Supports aria-invalid for error state."],
      usage: ["Use for notes, prompts, comments, and descriptions."],
      avoid: ["Do not use for single-line values."],
    },
    name: "textarea",
    registryDependencies: [],
    title: "Textarea",
    valueExports: ["Textarea"],
  },
  {
    dependencies: [],
    description: "Form field composition for label, help text, and error states.",
    exports: ["FieldProps", "Field", "FieldLabel", "FieldDescription", "FieldError", "FieldGroup"],
    importPath: "@brilliant/ui/field",
    kind: "component",
    metadata: {
      purpose: "Composes labels, controls, descriptions, and validation messages.",
      slots: ["root", "label", "description", "error", "group"],
      accessibility: [
        "Use htmlFor on FieldLabel to connect it to the control.",
        "Use aria-describedby to connect descriptions and errors.",
        "FieldError uses role alert.",
      ],
      usage: ["Use for every non-trivial form control.", "Keep error copy specific."],
      avoid: ["Do not rely on placeholder text as the only label."],
    },
    name: "field",
    registryDependencies: [],
    title: "Field",
    valueExports: ["Field", "FieldLabel", "FieldDescription", "FieldError", "FieldGroup"],
  },
  {
    dependencies: [],
    description: "A native checkbox with tokenized states and press micro UX.",
    exports: ["CheckboxProps", "Checkbox"],
    importPath: "@brilliant/ui/checkbox",
    kind: "component",
    metadata: {
      purpose: "Toggles a binary option or selects items in a set.",
      slots: ["root", "input", "control", "indicator"],
      accessibility: [
        "Uses a native checkbox input.",
        "Pair with a visible label.",
        "Supports indeterminate state for mixed selections.",
        "Focus is always visible for keyboard users.",
      ],
      usage: [
        "Use for independent boolean choices.",
        "Use size lg when the checkbox is the primary control in a settings row.",
        "Use indeterminate for partial table or tree selections.",
        "Use variant critical only for destructive selection contexts.",
      ],
      avoid: ["Do not use for immediate on/off settings when Switch is clearer."],
    },
    name: "checkbox",
    registryDependencies: [],
    title: "Checkbox",
    valueExports: ["Checkbox"],
  },
  {
    dependencies: [],
    description: "A native switch-style checkbox for immediate on/off settings.",
    exports: ["SwitchProps", "Switch"],
    importPath: "@brilliant/ui/switch",
    kind: "component",
    metadata: {
      purpose: "Toggles an immediate setting.",
      slots: ["root", "thumb"],
      accessibility: ["Uses a native checkbox with role switch.", "Pair with a visible label."],
      usage: ["Use for settings that take effect immediately."],
      avoid: ["Do not use for form submission choices that need review."],
    },
    name: "switch",
    registryDependencies: [],
    title: "Switch",
    valueExports: ["Switch"],
  },
  {
    dependencies: [],
    description: "A native radio choice group with tokenized states and dot micro UX.",
    exports: ["RadioGroupProps", "RadioGroup", "RadioItemProps", "RadioItem"],
    importPath: "@brilliant/ui/radio-group",
    kind: "component",
    metadata: {
      purpose: "Lets users choose exactly one option from a related set.",
      slots: ["root", "item", "input", "control", "indicator", "label", "description"],
      accessibility: [
        "Uses native radio inputs for form submission and keyboard behavior.",
        "Give related items the same name.",
        "Label the group with a legend or aria-label.",
        "Focus is always visible for keyboard users.",
      ],
      usage: [
        "Use for mutually exclusive choices.",
        "Use description for plan, permission, or policy context.",
        "Use orientation horizontal only for short, low-density choices.",
        "Use variant critical only for high-risk choices.",
      ],
      avoid: ["Do not use when multiple selections are allowed; use Checkbox instead."],
    },
    name: "radio-group",
    registryDependencies: [],
    title: "Radio Group",
    valueExports: ["RadioGroup", "RadioItem"],
  },
  {
    dependencies: [],
    description: "A native range control with Brilliant focus and thumb styling.",
    exports: ["SliderProps", "Slider"],
    importPath: "@brilliant/ui/slider",
    kind: "component",
    metadata: {
      purpose: "Adjusts a numeric value within a bounded range.",
      slots: ["root", "track", "thumb"],
      accessibility: [
        "Uses a native range input.",
        "Provide aria-label or a connected label.",
        "Keyboard behavior is handled by the browser.",
      ],
      usage: [
        "Use for continuous values.",
        "Use visible min/max/value text when precision matters.",
      ],
      avoid: ["Do not use for exact numeric entry without an input fallback."],
    },
    name: "slider",
    registryDependencies: [],
    title: "Slider",
    valueExports: ["Slider"],
  },
  {
    dependencies: ["@radix-ui/react-select"],
    description: "A Radix-powered select with Brilliant trigger, dropdown, and item styling.",
    exports: [
      "Select",
      "SelectGroup",
      "SelectValue",
      "SelectTrigger",
      "SelectContent",
      "SelectLabel",
      "SelectItem",
      "SelectSeparator",
    ],
    importPath: "@brilliant/ui/select",
    kind: "component",
    metadata: {
      purpose: "Chooses one option from a compact, fully styled dropdown menu.",
      slots: ["root", "trigger", "value", "content", "viewport", "item", "indicator"],
      accessibility: [
        "Uses Radix Select for keyboard navigation and managed ARIA behavior.",
        "Pair the trigger with a visible label or aria-label.",
        "Items expose selected and highlighted states without relying on color alone.",
      ],
      usage: [
        "Use for short known option lists.",
        "Use SelectItem for every selectable option.",
        "Prefer Combobox or Command when users need search.",
      ],
      avoid: ["Do not use for native mobile-only pickers where OS controls are required."],
    },
    name: "select",
    registryDependencies: [],
    title: "Select",
    valueExports: [
      "Select",
      "SelectGroup",
      "SelectValue",
      "SelectTrigger",
      "SelectContent",
      "SelectLabel",
      "SelectItem",
      "SelectSeparator",
    ],
  },
  {
    dependencies: [],
    description: "A styled searchable listbox combobox with Brilliant micro UX.",
    exports: ["ComboboxOption", "ComboboxProps", "Combobox"],
    importPath: "@brilliant/ui/combobox",
    kind: "component",
    metadata: {
      purpose: "Lets users type or choose from suggested options.",
      slots: ["root", "input", "listbox", "option", "indicator", "empty"],
      accessibility: [
        "Uses combobox and listbox roles with active descendant state.",
        "Pair with a visible label or aria-label.",
        "Supports keyboard open, close, arrow navigation, and enter selection.",
      ],
      usage: [
        "Use for searchable suggestions and short-to-medium option lists.",
        "Pass options as value/label objects.",
        "Use Command for richer command palettes or grouped actions.",
      ],
      avoid: [
        "Do not use for very large async datasets without virtualization or server filtering.",
      ],
    },
    name: "combobox",
    registryDependencies: [],
    title: "Combobox",
    valueExports: ["Combobox"],
  },
  {
    dependencies: [],
    description: "A semantic message surface for status, guidance, and errors.",
    exports: ["AlertProps", "Alert", "AlertTitle", "AlertDescription"],
    importPath: "@brilliant/ui/alert",
    kind: "component",
    metadata: {
      purpose: "Communicates important contextual feedback.",
      slots: ["root", "title", "description"],
      accessibility: ["Uses role status by default.", "Use clear text, not color alone."],
      usage: ["Use near the related task or form region."],
      avoid: ["Do not overuse persistent alerts."],
    },
    name: "alert",
    registryDependencies: [],
    title: "Alert",
    valueExports: ["Alert", "AlertTitle", "AlertDescription"],
  },
  {
    dependencies: [],
    description: "A native modal surface with header, content, and footer slots.",
    exports: [
      "DialogProps",
      "Dialog",
      "DialogHeader",
      "DialogTitle",
      "DialogDescription",
      "DialogContent",
      "DialogFooter",
    ],
    importPath: "@brilliant/ui/dialog",
    kind: "component",
    metadata: {
      purpose: "Shows focused content or tasks above the page.",
      slots: ["root", "header", "title", "description", "content", "footer"],
      accessibility: ["Uses native dialog semantics.", "Use showModal() and provide a title."],
      usage: ["Use for focused tasks.", "Keep actions in the footer."],
      avoid: ["Do not put long multi-page flows in one dialog."],
    },
    name: "dialog",
    registryDependencies: [],
    title: "Dialog",
    valueExports: [
      "Dialog",
      "DialogHeader",
      "DialogTitle",
      "DialogDescription",
      "DialogContent",
      "DialogFooter",
    ],
  },
  {
    dependencies: [],
    description: "A confirmation dialog for destructive or high-risk decisions.",
    exports: [
      "AlertDialogProps",
      "AlertDialog",
      "AlertDialogHeader",
      "AlertDialogTitle",
      "AlertDialogDescription",
      "AlertDialogContent",
      "AlertDialogFooter",
    ],
    importPath: "@brilliant/ui/alert-dialog",
    kind: "component",
    metadata: {
      purpose: "Confirms destructive, irreversible, or high-risk actions.",
      slots: ["root", "header", "title", "description", "content", "footer"],
      accessibility: ["Uses native dialog semantics.", "Use clear confirm and cancel actions."],
      usage: ["Use for destructive confirmation.", "Make consequences explicit."],
      avoid: ["Do not use for ordinary informational messages."],
    },
    name: "alert-dialog",
    registryDependencies: [],
    title: "Alert Dialog",
    valueExports: [
      "AlertDialog",
      "AlertDialogHeader",
      "AlertDialogTitle",
      "AlertDialogDescription",
      "AlertDialogContent",
      "AlertDialogFooter",
    ],
  },
  {
    dependencies: [],
    description: "A native dialog-based drawer for bottom or side panels.",
    exports: [
      "DrawerProps",
      "Drawer",
      "DrawerHeader",
      "DrawerTitle",
      "DrawerDescription",
      "DrawerContent",
    ],
    importPath: "@brilliant/ui/drawer",
    kind: "component",
    metadata: {
      purpose: "Shows contextual panels without leaving the page.",
      slots: ["root", "header", "title", "description", "content"],
      accessibility: ["Uses native dialog semantics.", "Provide a title."],
      usage: ["Use for mobile panels and contextual editors."],
      avoid: ["Do not hide primary page navigation in nested drawers."],
    },
    name: "drawer",
    registryDependencies: [],
    title: "Drawer",
    valueExports: ["Drawer", "DrawerHeader", "DrawerTitle", "DrawerDescription", "DrawerContent"],
  },
  {
    dependencies: [],
    description: "A side-panel primitive for settings, filters, and secondary workflows.",
    exports: [
      "SheetProps",
      "Sheet",
      "SheetHeader",
      "SheetTitle",
      "SheetDescription",
      "SheetContent",
    ],
    importPath: "@brilliant/ui/sheet",
    kind: "component",
    metadata: {
      purpose: "Shows secondary workflows in a side or edge panel.",
      slots: ["root", "header", "title", "description", "content"],
      accessibility: ["Uses native dialog semantics.", "Provide a title."],
      usage: ["Use for filters, settings, and object details."],
      avoid: ["Do not use sheets for global blocking confirmations."],
    },
    name: "sheet",
    registryDependencies: [],
    title: "Sheet",
    valueExports: ["Sheet", "SheetHeader", "SheetTitle", "SheetDescription", "SheetContent"],
  },
  {
    dependencies: ["@radix-ui/react-dropdown-menu"],
    description: "A Radix-powered contextual menu for secondary actions and option sets.",
    exports: [
      "DropdownMenu",
      "DropdownMenuTrigger",
      "DropdownMenuGroup",
      "DropdownMenuPortal",
      "DropdownMenuContent",
      "DropdownMenuItem",
      "DropdownMenuCheckboxItem",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuLabel",
      "DropdownMenuSeparator",
    ],
    importPath: "@brilliant/ui/dropdown-menu",
    kind: "component",
    metadata: {
      purpose: "Shows contextual actions from a trigger without taking over the page.",
      slots: [
        "root",
        "trigger",
        "content",
        "item",
        "checkbox-item",
        "radio-item",
        "label",
        "separator",
      ],
      accessibility: [
        "Uses Radix Dropdown Menu for keyboard navigation and menu semantics.",
        "Keep destructive actions clearly labeled.",
        "Do not make menu-only actions essential.",
      ],
      usage: [
        "Use for secondary object actions.",
        "Use checkbox or radio items for compact menu preferences.",
        "Keep menus short and grouped with labels or separators.",
      ],
      avoid: ["Do not use dropdown menus for primary page navigation."],
    },
    name: "dropdown-menu",
    registryDependencies: [],
    title: "Dropdown Menu",
    valueExports: [
      "DropdownMenu",
      "DropdownMenuTrigger",
      "DropdownMenuGroup",
      "DropdownMenuPortal",
      "DropdownMenuContent",
      "DropdownMenuItem",
      "DropdownMenuCheckboxItem",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuLabel",
      "DropdownMenuSeparator",
    ],
  },
  {
    dependencies: [],
    description: "A small hover/focus hint for controls and terse UI.",
    exports: ["TooltipProps", "Tooltip"],
    importPath: "@brilliant/ui/tooltip",
    kind: "component",
    metadata: {
      purpose: "Adds short non-essential helper text.",
      slots: ["root", "trigger", "content"],
      accessibility: ["Visible on hover and focus-within.", "Keep content short."],
      usage: ["Use for icon buttons and terse controls."],
      avoid: ["Do not hide required instructions only in a tooltip."],
    },
    name: "tooltip",
    registryDependencies: [],
    title: "Tooltip",
    valueExports: ["Tooltip"],
  },
  {
    dependencies: [],
    description: "A lightweight disclosure popover for compact contextual content.",
    exports: ["PopoverProps", "Popover", "PopoverTrigger", "PopoverContent"],
    importPath: "@brilliant/ui/popover",
    kind: "component",
    metadata: {
      purpose: "Reveals compact contextual content.",
      slots: ["root", "trigger", "content"],
      accessibility: ["Uses native details/summary disclosure behavior."],
      usage: ["Use for compact filters, quick settings, and small menus."],
      avoid: ["Do not use for destructive confirmation."],
    },
    name: "popover",
    registryDependencies: [],
    title: "Popover",
    valueExports: ["Popover", "PopoverTrigger", "PopoverContent"],
  },
  {
    dependencies: [],
    description: "A hover/focus card for richer previews.",
    exports: ["HoverCardProps", "HoverCard", "HoverCardTrigger", "HoverCardContent"],
    importPath: "@brilliant/ui/hover-card",
    kind: "component",
    metadata: {
      purpose: "Shows a richer preview for an object or person.",
      slots: ["root", "trigger", "content"],
      accessibility: [
        "Use only for supplemental information.",
        "Do not require hover-only content.",
      ],
      usage: ["Use for user, team, or object previews."],
      avoid: ["Do not hide required actions inside hover cards."],
    },
    name: "hover-card",
    registryDependencies: [],
    title: "Hover Card",
    valueExports: ["HoverCard", "HoverCardTrigger", "HoverCardContent"],
  },
  {
    dependencies: [],
    description: "A right-click contextual action menu.",
    exports: ["ContextMenuProps", "ContextMenu"],
    importPath: "@brilliant/ui/context-menu",
    kind: "component",
    metadata: {
      purpose: "Provides contextual actions for an object or region.",
      slots: ["root", "menu", "item"],
      accessibility: [
        "Expose critical actions elsewhere too.",
        "Keyboard-managed menu can be upgraded with Radix.",
      ],
      usage: ["Use for secondary object actions."],
      avoid: ["Do not make context menu the only way to complete a key task."],
    },
    name: "context-menu",
    registryDependencies: [],
    title: "Context Menu",
    valueExports: ["ContextMenu"],
  },
  {
    dependencies: [],
    description: "A semantic divider for grouping related content.",
    exports: ["SeparatorProps", "Separator"],
    importPath: "@brilliant/ui/separator",
    kind: "component",
    metadata: {
      purpose: "Separates content groups visually and semantically.",
      slots: ["root"],
      accessibility: [
        "Decorative by default.",
        "Set decorative=false when the separator conveys meaningful structure.",
        "Sets aria-orientation for non-decorative separators.",
      ],
      usage: [
        "Use variant default for normal dividers.",
        "Use variant muted for subtle grouping.",
        "Use variant primary only for active or branded section breaks.",
      ],
      avoid: ["Do not use as decoration when spacing is enough."],
    },
    name: "separator",
    registryDependencies: [],
    title: "Separator",
    valueExports: ["Separator"],
  },
  {
    dependencies: [],
    description: "A loading placeholder with shimmer, shape presets, and reduced-motion behavior.",
    exports: ["SkeletonProps", "Skeleton"],
    importPath: "@brilliant/ui/skeleton",
    kind: "component",
    metadata: {
      purpose: "Reserves layout space while content loads.",
      slots: ["root"],
      accessibility: [
        "Hidden from assistive technology.",
        "Pair with real loading state when needed.",
        "Shimmer animation is disabled for reduced-motion users.",
      ],
      usage: [
        "Use size text or title for copy placeholders.",
        "Use size avatar, thumbnail, or card to match incoming layout.",
        "Use variant raised or primary only when the loading surface needs stronger hierarchy.",
      ],
      avoid: ["Do not show skeletons for very fast operations."],
    },
    name: "skeleton",
    registryDependencies: [],
    title: "Skeleton",
    valueExports: ["Skeleton"],
  },
  {
    dependencies: [],
    description: "A determinate or indeterminate progress indicator with tokenized motion.",
    exports: ["ProgressProps", "Progress"],
    importPath: "@brilliant/ui/progress",
    kind: "component",
    metadata: {
      purpose: "Shows task completion or ongoing work.",
      slots: ["root", "indicator"],
      accessibility: [
        "Uses role progressbar.",
        "Sets aria-valuenow only for determinate progress.",
        "Provide aria-label or connect visible text with aria-labelledby.",
        "Indeterminate motion is disabled for reduced-motion users.",
      ],
      usage: [
        "Use value and max for known progress.",
        "Use indeterminate when progress cannot be measured.",
        "Keep critical progress for risky, blocking, or destructive flows.",
      ],
      avoid: ["Do not show fake percentages when progress is unknown."],
    },
    name: "progress",
    registryDependencies: [],
    title: "Progress",
    valueExports: ["Progress"],
  },
  {
    dependencies: [],
    description: "A compact loading status primitive with accessible status text.",
    exports: ["SpinnerProps", "Spinner"],
    importPath: "@brilliant/ui/spinner",
    kind: "component",
    metadata: {
      purpose: "Indicates short, local loading work.",
      slots: ["root", "icon", "label"],
      accessibility: [
        "Uses role status.",
        "Includes screen-reader-only loading text by default.",
        "Animation is disabled for reduced-motion users.",
      ],
      usage: [
        "Use inside buttons, table cells, and compact loading regions.",
        "Set label to describe the loading operation for assistive technology.",
        "Use muted when the spinner is secondary to nearby loading copy.",
      ],
      avoid: ["Do not use for long-running work without descriptive progress text."],
    },
    name: "spinner",
    registryDependencies: [],
    title: "Spinner",
    valueExports: ["Spinner"],
  },
  {
    dependencies: [],
    description: "A calm empty-region primitive for no data, no results, and first-run states.",
    exports: [
      "EmptyStateProps",
      "EmptyState",
      "EmptyStateIconProps",
      "EmptyStateIcon",
      "EmptyStateTitle",
      "EmptyStateDescription",
      "EmptyStateActions",
    ],
    importPath: "@brilliant/ui/empty-state",
    kind: "component",
    metadata: {
      purpose: "Explains why a region is empty and offers a useful next action.",
      slots: ["root", "icon", "title", "description", "actions"],
      accessibility: [
        "Uses semantic headings authored by the consumer.",
        "Actions remain real buttons or links.",
        "Entry motion is disabled for reduced-motion users.",
      ],
      usage: [
        "Use title and description to explain the empty state clearly.",
        "Use actions only when there is a meaningful next step.",
        "Use ghost inside already bordered parent surfaces.",
      ],
      avoid: ["Do not use empty states as marketing panels inside component docs."],
    },
    name: "empty-state",
    registryDependencies: [],
    title: "Empty State",
    valueExports: [
      "EmptyState",
      "EmptyStateIcon",
      "EmptyStateTitle",
      "EmptyStateDescription",
      "EmptyStateActions",
    ],
  },
  {
    dependencies: ["@radix-ui/react-tabs"],
    description: "A Radix-powered tab primitive for switching related panels.",
    exports: ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
    importPath: "@brilliant/ui/tabs",
    kind: "component",
    metadata: {
      purpose: "Switches between related content panels.",
      slots: ["root", "list", "trigger", "content"],
      accessibility: [
        "Uses Radix Tabs for tablist, tab, tabpanel, roving focus, and keyboard behavior.",
        "Use matching value props on triggers and content panels.",
        "Focus states are visible for keyboard users.",
      ],
      usage: [
        "Use for peer sections of one context.",
        "Keep tab labels short.",
        "Use defaultValue for uncontrolled tabs or value/onValueChange for controlled tabs.",
      ],
      avoid: ["Do not use tabs as primary page navigation."],
    },
    name: "tabs",
    registryDependencies: [],
    title: "Tabs",
    valueExports: ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
  },
  {
    dependencies: [],
    description: "A details-based accordion for stacked disclosure sections.",
    exports: [
      "AccordionProps",
      "Accordion",
      "AccordionItem",
      "AccordionTrigger",
      "AccordionContent",
    ],
    importPath: "@brilliant/ui/accordion",
    kind: "component",
    metadata: {
      purpose: "Shows and hides stacked sections.",
      slots: ["root", "item", "trigger", "content"],
      accessibility: ["Uses native details/summary disclosure behavior."],
      usage: ["Use for FAQs, settings groups, and optional detail sections."],
      avoid: ["Do not hide required form fields in collapsed sections by default."],
    },
    name: "accordion",
    registryDependencies: [],
    title: "Accordion",
    valueExports: ["Accordion", "AccordionItem", "AccordionTrigger", "AccordionContent"],
  },
  {
    dependencies: [],
    description: "A single disclosure primitive for optional content.",
    exports: [
      "CollapsibleProps",
      "Collapsible",
      "CollapsibleItem",
      "CollapsibleTrigger",
      "CollapsibleContent",
    ],
    importPath: "@brilliant/ui/collapsible",
    kind: "component",
    metadata: {
      purpose: "Shows or hides one content region.",
      slots: ["root", "trigger", "content"],
      accessibility: ["Uses native details/summary disclosure behavior."],
      usage: ["Use for optional controls and advanced sections."],
      avoid: ["Do not hide critical information by default."],
    },
    name: "collapsible",
    registryDependencies: [],
    title: "Collapsible",
    valueExports: ["Collapsible", "CollapsibleItem", "CollapsibleTrigger", "CollapsibleContent"],
  },
  {
    dependencies: [],
    description: "A controlled carousel primitive with viewport, track, items, controls, and dots.",
    exports: [
      "CarouselProps",
      "Carousel",
      "CarouselViewport",
      "CarouselTrack",
      "CarouselItem",
      "CarouselPrevious",
      "CarouselNext",
      "CarouselDots",
    ],
    importPath: "@brilliant/ui/carousel",
    kind: "component",
    metadata: {
      purpose: "Displays a small sequence of cards or previews with explicit navigation controls.",
      slots: ["root", "viewport", "track", "item", "previous", "next", "dots"],
      accessibility: [
        "Navigation controls have accessible labels.",
        "Disabled controls communicate start and end positions.",
        "Do not auto-advance content.",
      ],
      usage: [
        "Use itemCount to wire control state.",
        "Use CarouselViewport, CarouselTrack, and CarouselItem for the slide structure.",
        "Use dots for short carousels where position matters.",
      ],
      avoid: ["Do not hide essential content in carousels."],
    },
    name: "carousel",
    registryDependencies: [],
    title: "Carousel",
    valueExports: [
      "Carousel",
      "CarouselViewport",
      "CarouselTrack",
      "CarouselItem",
      "CarouselPrevious",
      "CarouselNext",
      "CarouselDots",
    ],
  },
  {
    dependencies: [],
    description: "A crisp semantic table primitive for enterprise data surfaces.",
    exports: [
      "Table",
      "TableHeader",
      "TableBody",
      "TableFooter",
      "TableRow",
      "TableHead",
      "TableCell",
      "TableCaption",
    ],
    importPath: "@brilliant/ui/table",
    kind: "component",
    metadata: {
      purpose: "Displays structured rows and columns with dense, readable defaults.",
      slots: ["root", "caption", "header", "body", "footer", "row", "head", "cell"],
      accessibility: [
        "Uses semantic table elements.",
        "Use TableHead for column headers.",
        "Add captions when context is not otherwise clear.",
      ],
      usage: [
        "Use for simple data display.",
        "Use selected row state with data-state=selected.",
        "Use Data Table blocks later for sorting, filtering, and pagination.",
      ],
      avoid: ["Do not use tables for layout."],
    },
    name: "table",
    registryDependencies: [],
    title: "Table",
    valueExports: [
      "Table",
      "TableHeader",
      "TableBody",
      "TableFooter",
      "TableRow",
      "TableHead",
      "TableCell",
      "TableCaption",
    ],
  },
  {
    dependencies: [],
    description: "A form composition primitive for sections, copy, and action rows.",
    exports: ["Form", "FormSection", "FormHeader", "FormTitle", "FormDescription", "FormActions"],
    importPath: "@brilliant/ui/form",
    kind: "component",
    metadata: {
      purpose: "Composes product-grade forms from sections, field groups, and action rows.",
      slots: ["root", "section", "header", "title", "description", "actions"],
      accessibility: [
        "Preserves native form semantics.",
        "Pair controls with Field and Label primitives.",
        "Use real submit buttons for form submission.",
      ],
      usage: [
        "Use FormSection for grouped settings.",
        "Use FormActions for cancel/save affordances.",
        "Use Field for label, description, and validation state.",
      ],
      avoid: ["Do not hide required fields in decorative cards."],
    },
    name: "form",
    registryDependencies: ["field"],
    title: "Form",
    valueExports: [
      "Form",
      "FormSection",
      "FormHeader",
      "FormTitle",
      "FormDescription",
      "FormActions",
    ],
  },
  {
    dependencies: ["@radix-ui/react-scroll-area"],
    description: "A Radix-powered scroll container with Brilliant scrollbar styling.",
    exports: ["ScrollArea", "ScrollBar"],
    importPath: "@brilliant/ui/scroll-area",
    kind: "component",
    metadata: {
      purpose: "Contains overflow content without browser-default scrollbar chrome.",
      slots: ["root", "viewport", "scrollbar", "thumb", "corner"],
      accessibility: [
        "Uses native scrolling behavior through Radix Scroll Area.",
        "Do not trap keyboard focus inside scroll regions.",
        "Give long regions a visible heading or label nearby.",
      ],
      usage: [
        "Use for menus, sidebars, activity feeds, and constrained panels.",
        "Keep essential content discoverable outside tiny scroll areas.",
      ],
      avoid: ["Do not replace normal page scrolling without a strong reason."],
    },
    name: "scroll-area",
    registryDependencies: [],
    title: "Scroll Area",
    valueExports: ["ScrollArea", "ScrollBar"],
  },
  {
    dependencies: [],
    description: "A semantic breadcrumb navigation primitive.",
    exports: ["Breadcrumb", "BreadcrumbList", "BreadcrumbItem", "BreadcrumbSeparator"],
    importPath: "@brilliant/ui/breadcrumb",
    kind: "component",
    metadata: {
      purpose: "Shows the current location in a hierarchy.",
      slots: ["root", "list", "item", "separator"],
      accessibility: ["Uses nav with aria-label Breadcrumb."],
      usage: ["Use for nested apps and object hierarchies."],
      avoid: ["Do not use as the only navigation."],
    },
    name: "breadcrumb",
    registryDependencies: [],
    title: "Breadcrumb",
    valueExports: ["Breadcrumb", "BreadcrumbList", "BreadcrumbItem", "BreadcrumbSeparator"],
  },
  {
    dependencies: [],
    description: "A simple semantic navigation menu primitive.",
    exports: ["NavigationMenu", "NavigationMenuLink"],
    importPath: "@brilliant/ui/navigation-menu",
    kind: "component",
    metadata: {
      purpose: "Groups primary or secondary navigation links.",
      slots: ["root", "link"],
      accessibility: ["Uses nav semantics.", "Links remain real anchors."],
      usage: ["Use for top bars and side sections."],
      avoid: ["Do not use buttons for navigation destinations."],
    },
    name: "navigation-menu",
    registryDependencies: [],
    title: "Navigation Menu",
    valueExports: ["NavigationMenu", "NavigationMenuLink"],
  },
  {
    dependencies: [],
    description:
      "A responsive site header with sticky, fixed, and static positioning plus built-in mobile navigation.",
    exports: [
      "HeaderScrollState",
      "HeaderProps",
      "Header",
      "HeaderContainer",
      "HeaderBrand",
      "HeaderNavProps",
      "HeaderNav",
      "HeaderLink",
      "HeaderActions",
      "HeaderMobileTrigger",
    ],
    importPath: "@brilliant/ui/header",
    kind: "layout",
    metadata: {
      purpose:
        "Provides persistent brand, primary navigation, and action placement for product and documentation surfaces.",
      slots: ["root", "container", "brand", "navigation", "link", "actions", "mobile-trigger"],
      accessibility: [
        "Uses semantic header and navigation elements.",
        "Active links expose aria-current=page.",
        "The mobile trigger exposes its expanded state and supports Escape to close.",
        "Navigation destinations remain real anchors.",
        "Decorative logo images inside HeaderBrand should use an empty alt when adjacent brand text supplies the accessible name.",
        "Reveal motion is disabled when the user prefers reduced motion.",
      ],
      usage: [
        "Use position=sticky for persistent navigation, static for normal document flow, or fixed for an overlaying global header.",
        "Use surface=solid for opaque application shells, translucent for a blurred overlay, or transparent when content should show through.",
        "Use behavior=elevate for subtle scroll separation, reveal to hide on downward scroll and return on upward scroll, or none for custom behavior.",
        "Style data-scrolled, data-scroll-direction, and data-visibility states to change color, transparency, density, or other presentation.",
        "Use onScrollStateChange when scroll state must change rendered content such as a logo or action set.",
        "Use HeaderContainer to constrain content width and align the brand, navigation, and actions.",
        "Set HeaderNav align to start, center, or end to position desktop navigation within the available header space.",
        "Set border to true when the application shell needs a persistent header separator; it is off by default.",
        "Place an img, inline SVG, or framework image component inside HeaderBrand alongside optional brand text.",
        "Use HeaderMobileTrigger to expose the navigation below the mobile breakpoint.",
      ],
      avoid: [
        "Do not use position=fixed without adding equivalent top spacing to the page content.",
        "Do not use large color or visibility shifts that make navigation feel unstable.",
        "Do not place large forms or multi-level application navigation in a site header.",
      ],
    },
    name: "header",
    registryDependencies: [],
    title: "Header",
    valueExports: [
      "Header",
      "HeaderContainer",
      "HeaderBrand",
      "HeaderNav",
      "HeaderLink",
      "HeaderActions",
      "HeaderMobileTrigger",
    ],
  },
  {
    dependencies: [],
    description:
      "A responsive footer composition with brand copy, grouped navigation, legal links, and surface variants.",
    exports: [
      "FooterProps",
      "Footer",
      "FooterContainer",
      "FooterMain",
      "FooterBrand",
      "FooterDescription",
      "FooterNav",
      "FooterGroup",
      "FooterLink",
      "FooterBottom",
    ],
    importPath: "@brilliant/ui/footer",
    kind: "layout",
    metadata: {
      purpose:
        "Closes product, documentation, and public pages with structured navigation and ownership information.",
      slots: [
        "root",
        "container",
        "main",
        "brand",
        "description",
        "navigation",
        "group",
        "link",
        "bottom",
      ],
      accessibility: [
        "Uses the semantic footer landmark.",
        "Footer navigation has an accessible label.",
        "Links preserve native anchor behavior and visible keyboard focus.",
        "Group headings provide context without creating fake navigation controls.",
      ],
      usage: [
        "Use variant=surface for most pages, muted for stronger separation, or transparent inside an existing surface.",
        "Use FooterGroup for compact, scannable link columns.",
        "Keep legal and copyright content in FooterBottom.",
      ],
      avoid: [
        "Do not duplicate the full application sidebar in the footer.",
        "Do not use low-contrast links or hide essential legal information.",
      ],
    },
    name: "footer",
    registryDependencies: [],
    title: "Footer",
    valueExports: [
      "Footer",
      "FooterContainer",
      "FooterMain",
      "FooterBrand",
      "FooterDescription",
      "FooterNav",
      "FooterGroup",
      "FooterLink",
      "FooterBottom",
    ],
  },
  {
    dependencies: [],
    description:
      "A responsive app frame with structured header actions, mobile navigation, and a pinned sidebar profile footer.",
    exports: [
      "ApplicationShellProps",
      "ApplicationShell",
      "ApplicationShellHeader",
      "ApplicationShellHeaderBrand",
      "ApplicationShellHeaderContent",
      "ApplicationShellHeaderTitle",
      "ApplicationShellHeaderDescription",
      "ApplicationShellHeaderActions",
      "ApplicationShellHeaderAction",
      "ApplicationShellMobileTrigger",
      "ApplicationShellSidebarToggle",
      "ApplicationShellSidebar",
      "ApplicationShellSidebarHeader",
      "ApplicationShellBrand",
      "ApplicationShellSidebarContent",
      "ApplicationShellSidebarFooter",
      "ApplicationShellSidebarFooterActions",
      "ApplicationShellSidebarFooterAction",
      "ApplicationShellSearch",
      "ApplicationShellNav",
      "ApplicationShellNavSection",
      "ApplicationShellNavItem",
      "ApplicationShellNavMedia",
      "ApplicationShellNavGroupItem",
      "ApplicationShellMenu",
      "ApplicationShellMenuSection",
      "ApplicationShellMenuItem",
      "ApplicationShellAccountSwitcher",
      "ApplicationShellProfile",
      "ApplicationShellProfileMenu",
      "ApplicationShellProfileTrigger",
      "ApplicationShellAccountItem",
      "ApplicationShellMain",
      "ApplicationShellFooter",
    ],
    importPath: "@brilliant/ui/application-shell",
    kind: "layout",
    metadata: {
      purpose:
        "Provides the outer frame for SaaS apps, dashboards, internal tools, and AI workspaces.",
      slots: [
        "root",
        "header",
        "header-brand",
        "header-content",
        "header-title",
        "header-description",
        "header-actions",
        "header-action",
        "mobile-trigger",
        "sidebar-toggle",
        "sidebar",
        "sidebar-header",
        "sidebar-content",
        "sidebar-footer",
        "sidebar-footer-actions",
        "sidebar-footer-action",
        "brand",
        "search",
        "nav",
        "nav-section",
        "nav-item",
        "nav-media",
        "nav-group-item",
        "menu",
        "menu-section",
        "menu-item",
        "menu-item-media",
        "account-switcher",
        "account-item",
        "profile",
        "profile-menu",
        "profile-trigger",
        "main",
        "footer",
      ],
      accessibility: [
        "Sidebar navigation uses nav and anchor semantics.",
        "Mobile navigation closes with Escape and backdrop click.",
        "Active navigation items expose aria-current.",
        "The mobile trigger is a native button with visible focus.",
        "The desktop sidebar toggle exposes its expanded state and an action-specific accessible name.",
        "Header actions use native buttons and require an accessible name when icon-only.",
        "HeaderBrand is a native link; decorative logo images should use an empty alt when the adjacent brand name supplies the accessible text.",
        "HeaderBrand is hidden on desktop by default because the sidebar brand is the canonical desktop identity.",
        "The profile menu uses native details and summary disclosure semantics.",
        "Scrollable sidebar content keeps native scrolling while suppressing the visual scrollbar; keyboard, wheel, and touch scrolling remain available.",
      ],
      usage: [
        "Use as the top-level frame for authenticated product screens.",
        "Place ApplicationShellSidebarToggle inside ApplicationShellSidebarHeader, aligned opposite the brand; mobile navigation remains controlled by ApplicationShellMobileTrigger.",
        "Use collapsed and onCollapsedChange when sidebar state must be controlled or persisted by the application.",
        "Keep primary navigation in ApplicationShellSidebar.",
        "Use NavItem for simple destinations and NavGroupItem for inbox/account rows with secondary text.",
        "Wrap navigation in SidebarContent and place the profile control in SidebarFooter so it remains visible while navigation scrolls.",
        "Use SidebarFooterActions for persistent utility actions such as help, notifications, appearance, or workspace settings.",
        "Use the built-in header, sidebar, and footer separators to communicate pane structure instead of styling a scrollbar as a divider.",
        "Compose Profile, ProfileMenu, and ProfileTrigger for account, workspace, settings, and sign-out actions.",
        "Use menu item icon for action glyphs and media for avatars/account bubbles.",
        "Compose HeaderContent, HeaderTitle, HeaderDescription, HeaderActions, and HeaderAction for page context and global actions.",
        "Use ApplicationShellBrand as the canonical desktop identity and HeaderBrand as the compact mobile fallback.",
        "Use ApplicationShellMain for route/page content.",
      ],
      avoid: [
        "Do not use for marketing pages or one-off landing layouts.",
        "Do not put every possible destination in the primary sidebar.",
        "Do not repeat the full brand in both the desktop sidebar and desktop header.",
      ],
    },
    name: "application-shell",
    registryDependencies: [],
    title: "Application Shell",
    valueExports: [
      "ApplicationShell",
      "ApplicationShellHeader",
      "ApplicationShellHeaderBrand",
      "ApplicationShellHeaderContent",
      "ApplicationShellHeaderTitle",
      "ApplicationShellHeaderDescription",
      "ApplicationShellHeaderActions",
      "ApplicationShellHeaderAction",
      "ApplicationShellMobileTrigger",
      "ApplicationShellSidebarToggle",
      "ApplicationShellSidebar",
      "ApplicationShellSidebarHeader",
      "ApplicationShellBrand",
      "ApplicationShellSidebarContent",
      "ApplicationShellSidebarFooter",
      "ApplicationShellSidebarFooterActions",
      "ApplicationShellSidebarFooterAction",
      "ApplicationShellSearch",
      "ApplicationShellNav",
      "ApplicationShellNavSection",
      "ApplicationShellNavItem",
      "ApplicationShellNavMedia",
      "ApplicationShellNavGroupItem",
      "ApplicationShellMenu",
      "ApplicationShellMenuSection",
      "ApplicationShellMenuItem",
      "ApplicationShellAccountSwitcher",
      "ApplicationShellProfile",
      "ApplicationShellProfileMenu",
      "ApplicationShellProfileTrigger",
      "ApplicationShellAccountItem",
      "ApplicationShellMain",
      "ApplicationShellFooter",
    ],
  },
  {
    dependencies: ["recharts", "react-is"],
    description:
      "A Recharts foundation with responsive sizing, semantic configuration, premium tooltips, legends, sparklines, and dashboard states.",
    exports: [
      "ChartConfig",
      "ChartContainerProps",
      "ChartContainer",
      "ChartTooltip",
      "ChartLegend",
      "ChartTooltipContent",
      "ChartLegendContent",
      "SparklineProps",
      "Sparkline",
      "ChartState",
    ],
    importPath: "@brilliant/ui/chart",
    kind: "component",
    metadata: {
      purpose:
        "Provides the shared visual, accessibility, responsive, tooltip, legend, and state contract for dashboard charts without hiding Recharts composition.",
      slots: [
        "container",
        "tooltip",
        "tooltip-content",
        "legend",
        "legend-content",
        "sparkline",
        "state",
      ],
      accessibility: [
        "ChartContainer requires a title and accepts a longer description for assistive technology.",
        "Enable accessibilityLayer on Recharts chart primitives for keyboard and screen-reader navigation.",
        "ChartState uses status or alert semantics for loading, empty, and error states.",
        "Recharts v3 automatic animation respects reduced-motion preferences.",
      ],
      usage: [
        "Compose LineChart, AreaChart, BarChart, PieChart, and other Recharts primitives inside ChartContainer.",
        "Define human-readable labels and tokenized colors in ChartConfig.",
        "Keep a fixed height, minimum height, or aspect ratio on ChartContainer so responsive measurement is stable.",
        "Use Sparkline inside compact stat cards and tables where axes would add noise.",
      ],
      avoid: [
        "Do not encode meaning with color alone.",
        "Do not render charts without a title or an equivalent accessible data summary.",
        "Do not use a chart when a single number or small table communicates the result more clearly.",
      ],
    },
    name: "chart",
    registryDependencies: [],
    title: "Chart",
    valueExports: [
      "ChartContainer",
      "ChartTooltip",
      "ChartLegend",
      "ChartTooltipContent",
      "ChartLegendContent",
      "Sparkline",
      "ChartState",
    ],
  },
  {
    dependencies: [],
    description:
      "Composable metrics, KPI cards, trend indicators, and dense dashboard values with restrained micro UX.",
    exports: [
      "Stat",
      "StatHeader",
      "StatLabel",
      "StatValue",
      "StatDescription",
      "TrendIndicator",
      "Metric",
    ],
    importPath: "@brilliant/ui/stat",
    kind: "component",
    metadata: {
      purpose:
        "Presents a primary metric with comparison, trend, context, and optional compact charting.",
      slots: ["root", "header", "label", "value", "description", "trend", "metric"],
      accessibility: [
        "Uses normal document semantics so consumers can choose the correct heading level.",
        "Trend arrows are decorative; direction must also be conveyed by text or value context.",
        "Tabular figures reduce visual movement when values update.",
      ],
      usage: [
        "Use Stat for dashboard KPI cards and Metric for compact label/value pairs.",
        "Use TrendIndicator only when a comparison period or baseline is explicit.",
        "Place Sparkline from the chart item beside a StatValue for compact trend context.",
      ],
      avoid: [
        "Do not label a change positive or negative based only on its mathematical direction.",
        "Do not fill every dashboard card with a trend badge when no useful comparison exists.",
      ],
    },
    name: "stat",
    registryDependencies: [],
    title: "Stat",
    valueExports: [
      "Stat",
      "StatHeader",
      "StatLabel",
      "StatValue",
      "StatDescription",
      "TrendIndicator",
      "Metric",
    ],
  },
  {
    dependencies: [],
    description:
      "Operational status dots, live-state indicators, and proportional status bars for dashboards.",
    exports: ["Status", "StatusBarItem", "StatusBar"],
    importPath: "@brilliant/ui/status",
    kind: "component",
    metadata: {
      purpose: "Communicates service state, health, presence, and category distribution.",
      slots: ["status", "indicator", "status-bar", "status-bar-segment", "legend"],
      accessibility: [
        "Visible text accompanies every status color.",
        "StatusBar exposes one accessible image label and a visible text legend.",
        "Pulse motion is disabled when reduced motion is preferred.",
      ],
      usage: [
        "Use Status for a named state and StatusBar for a proportional distribution.",
        "Use pulse only for genuinely live or actively changing states.",
        "Choose positive, warning, critical, or neutral based on product meaning.",
      ],
      avoid: [
        "Do not use pulse as decoration.",
        "Do not rely on green, amber, or red without accompanying text.",
      ],
    },
    name: "status",
    registryDependencies: [],
    title: "Status",
    valueExports: ["Status", "StatusBar"],
  },
  {
    dependencies: [],
    description:
      "A labeled scalar measurement for quotas, capacity, budgets, and dashboard utilization.",
    exports: ["Meter"],
    importPath: "@brilliant/ui/meter",
    kind: "component",
    metadata: {
      purpose: "Shows a current scalar value within a known range, distinct from task progress.",
      slots: ["root", "label", "value", "track", "indicator"],
      accessibility: [
        "Uses the native meter element for assistive technology.",
        "The visual bar is hidden from assistive technology to prevent duplicate announcements.",
        "Value and maximum are clamped into a stable visual percentage.",
      ],
      usage: [
        "Use Meter for usage, quotas, budgets, storage, and capacity.",
        "Use Progress instead for completion of an ongoing task.",
        "Use warning or critical tones only when thresholds carry product meaning.",
      ],
      avoid: [
        "Do not use Meter for an indeterminate operation.",
        "Do not change tone without explaining the threshold elsewhere in the interface.",
      ],
    },
    name: "meter",
    registryDependencies: [],
    title: "Meter",
    valueExports: ["Meter"],
  },
  {
    dependencies: [],
    description:
      "Responsive dashboard page structure with headers, actions, KPI grids, and composable content sections.",
    exports: [
      "DashboardLayout",
      "DashboardHeader",
      "DashboardTitle",
      "DashboardDescription",
      "DashboardActions",
      "DashboardGrid",
      "DashboardSection",
      "DashboardSectionHeader",
      "DashboardSectionTitle",
    ],
    importPath: "@brilliant/ui/dashboard-layout",
    kind: "layout",
    metadata: {
      purpose:
        "Standardizes responsive dashboard page hierarchy without prescribing business content.",
      slots: [
        "root",
        "header",
        "title",
        "description",
        "actions",
        "grid",
        "section",
        "section-header",
        "section-title",
      ],
      accessibility: [
        "Uses semantic header, section, and heading elements.",
        "Consumers remain responsible for one logical page heading and unique section labels.",
        "Responsive grids preserve DOM and reading order.",
      ],
      usage: [
        "Use inside ApplicationShellMain for authenticated dashboard routes.",
        "Compose Stat, Chart, Status, Meter, Card, Table, and filter controls inside sections.",
        "Keep actions close to the dashboard or section they affect.",
      ],
      avoid: [
        "Do not use visual grid order to contradict document reading order.",
        "Do not turn every dashboard section into an unrelated card.",
      ],
    },
    name: "dashboard-layout",
    registryDependencies: [],
    title: "Dashboard Layout",
    valueExports: [
      "DashboardLayout",
      "DashboardHeader",
      "DashboardTitle",
      "DashboardDescription",
      "DashboardActions",
      "DashboardGrid",
      "DashboardSection",
      "DashboardSectionHeader",
      "DashboardSectionTitle",
    ],
  },
  {
    dependencies: ["recharts", "react-is"],
    description:
      "A responsive analytics dashboard with KPI trends and an accessible revenue chart.",
    exports: ["AnalyticsOverviewDashboard"],
    importPath: "@brilliant/ui/analytics-overview-dashboard",
    kind: "block",
    metadata: {
      purpose: "Provides a production-ready executive analytics overview for SaaS products.",
      slots: ["kpi-grid", "trend-chart", "reporting-context"],
      accessibility: [
        "The chart has an accessible title and Recharts accessibility layer.",
        "Trend direction is expressed with a value and arrow, not color alone.",
        "The responsive grid preserves source order.",
      ],
      usage: [
        "Install as a route-level dashboard block and replace the example data with product data.",
        "Keep reporting ranges and comparison baselines explicit.",
      ],
      avoid: [
        "Do not show KPIs without a defined reporting period.",
        "Do not add chart series that do not support a concrete decision.",
      ],
    },
    name: "analytics-overview-dashboard",
    registryDependencies: ["chart", "dashboard-layout", "stat"],
    title: "Analytics Overview Dashboard",
    valueExports: ["AnalyticsOverviewDashboard"],
  },
  {
    dependencies: [],
    description:
      "An operational dashboard for uptime, latency, service health, incidents, and capacity.",
    exports: ["SystemHealthDashboard"],
    importPath: "@brilliant/ui/system-health-dashboard",
    kind: "block",
    metadata: {
      purpose: "Summarizes live production health without relying on decorative telemetry.",
      slots: ["health-kpis", "live-status", "service-list", "capacity-meter"],
      accessibility: [
        "Every service state has visible text in addition to color.",
        "The live indicator respects reduced-motion preferences.",
        "Status distribution exposes an accessible summary.",
      ],
      usage: [
        "Connect status values to monitored service data.",
        "Use live pulse only while telemetry is actively updating.",
      ],
      avoid: [
        "Do not use healthy colors to conceal partial outages.",
        "Do not display stale telemetry without an updated-at timestamp.",
      ],
    },
    name: "system-health-dashboard",
    registryDependencies: ["dashboard-layout", "meter", "stat", "status"],
    title: "System Health Dashboard",
    valueExports: ["SystemHealthDashboard"],
  },
  {
    dependencies: ["recharts", "react-is"],
    description: "A stacked capacity comparison with quota meters for storage, events, and seats.",
    exports: ["CapacityDashboard"],
    importPath: "@brilliant/ui/capacity-dashboard",
    kind: "block",
    metadata: {
      purpose: "Makes team-level utilization and quota risk directly comparable.",
      slots: ["stacked-chart", "quota-meters", "billing-period"],
      accessibility: [
        "The chart exposes an accessible title and keyboard layer.",
        "Meters use native scalar semantics.",
        "Warning and critical states include visible labels and values.",
      ],
      usage: [
        "Use for quotas with known minimum and maximum values.",
        "Keep used and available values on the same scale.",
      ],
      avoid: [
        "Do not use stacked bars for unrelated measures.",
        "Do not imply risk thresholds that the product does not enforce.",
      ],
    },
    name: "capacity-dashboard",
    registryDependencies: ["chart", "dashboard-layout", "meter"],
    title: "Capacity Dashboard",
    valueExports: ["CapacityDashboard"],
  },
  {
    dependencies: [],
    description:
      "A premium multi-step onboarding flow with step rail, progress, content panel, and actions.",
    exports: [
      "OnboardingWizardProps",
      "OnboardingWizard",
      "OnboardingWizardHeader",
      "OnboardingWizardTitle",
      "OnboardingWizardDescription",
      "OnboardingWizardProgress",
      "OnboardingWizardStepList",
      "OnboardingWizardStep",
      "OnboardingWizardPanel",
      "OnboardingWizardMeta",
      "OnboardingWizardContent",
      "OnboardingWizardActions",
    ],
    importPath: "@brilliant/ui/onboarding-wizard",
    kind: "layout",
    metadata: {
      purpose:
        "Guides users through product setup, activation, import, provisioning, or first-run workflows.",
      slots: [
        "root",
        "header",
        "title",
        "description",
        "progress",
        "step-list",
        "step",
        "panel",
        "meta",
        "content",
        "actions",
      ],
      accessibility: [
        "Current step exposes aria-current=step.",
        "Step controls are native buttons with visible focus.",
        "Progress includes visible text and a tokenized progress track.",
        "Entry and interaction motion respects reduced-motion preferences.",
      ],
      usage: [
        "Use for first-run onboarding, workspace setup, imports, and activation checklists.",
        "Keep active step state in the app so form data and navigation are explicit.",
        "Use complete/current/upcoming step states to show progress without hiding skipped steps.",
        "Put real form fields, uploads, or integration cards inside OnboardingWizardContent.",
      ],
      avoid: [
        "Do not use for one-screen settings forms.",
        "Do not block users with unnecessary onboarding steps.",
        "Do not rely only on color to communicate step status.",
      ],
    },
    name: "onboarding-wizard",
    registryDependencies: [],
    title: "Onboarding Wizard",
    valueExports: [
      "OnboardingWizard",
      "OnboardingWizardHeader",
      "OnboardingWizardTitle",
      "OnboardingWizardDescription",
      "OnboardingWizardProgress",
      "OnboardingWizardStepList",
      "OnboardingWizardStep",
      "OnboardingWizardPanel",
      "OnboardingWizardMeta",
      "OnboardingWizardContent",
      "OnboardingWizardActions",
    ],
  },
  {
    dependencies: [],
    description: "A compact command menubar primitive.",
    exports: ["Menubar", "MenubarItem"],
    importPath: "@brilliant/ui/menubar",
    kind: "component",
    metadata: {
      purpose: "Groups app-level commands.",
      slots: ["root", "item"],
      accessibility: ["Uses menubar and menuitem roles."],
      usage: ["Use for dense app command surfaces."],
      avoid: ["Do not use menubars for ordinary page links."],
    },
    name: "menubar",
    registryDependencies: [],
    title: "Menubar",
    valueExports: ["Menubar", "MenubarItem"],
  },
  {
    dependencies: [],
    description: "A semantic pagination navigation primitive.",
    exports: ["Pagination", "PaginationList", "PaginationItem", "PaginationLink"],
    importPath: "@brilliant/ui/pagination",
    kind: "component",
    metadata: {
      purpose: "Navigates paged collections.",
      slots: ["root", "list", "item", "link"],
      accessibility: [
        "Uses nav with aria-label Pagination.",
        "Use aria-current on the current page.",
      ],
      usage: ["Use for paged tables and lists."],
      avoid: ["Do not use pagination for tiny collections."],
    },
    name: "pagination",
    registryDependencies: [],
    title: "Pagination",
    valueExports: ["Pagination", "PaginationList", "PaginationItem", "PaginationLink"],
  },
  {
    dependencies: [],
    description: "A provider-backed toast system for transient status messages.",
    exports: [
      "ToastMessage",
      "ToastProvider",
      "useToast",
      "ToastRegion",
      "Toast",
      "ToastTitle",
      "ToastDescription",
      "ToastClose",
    ],
    importPath: "@brilliant/ui/toast",
    kind: "component",
    metadata: {
      purpose: "Shows transient non-blocking feedback.",
      slots: ["provider", "region", "toast", "title", "description", "close"],
      accessibility: [
        "ToastRegion uses aria-live polite and role region.",
        "Toast uses role status.",
        "Close controls have accessible labels.",
        "Do not rely on toast for critical decisions.",
      ],
      usage: [
        "Wrap the app or route segment in ToastProvider.",
        "Call useToast().toast(...) from event handlers.",
        "Use variants for default, primary, or critical non-blocking feedback.",
      ],
      avoid: ["Do not use toast as the only error recovery path."],
    },
    name: "toast",
    registryDependencies: [],
    title: "Toast",
    valueExports: [
      "ToastProvider",
      "useToast",
      "ToastRegion",
      "Toast",
      "ToastTitle",
      "ToastDescription",
      "ToastClose",
    ],
  },
  {
    dependencies: [],
    description: "A table foundation for calendar/date-picker composition.",
    exports: ["CalendarProps", "Calendar"],
    importPath: "@brilliant/ui/calendar",
    kind: "component",
    metadata: {
      purpose: "Provides a semantic calendar table foundation.",
      slots: ["root", "caption", "row", "cell"],
      accessibility: ["Use table headings for weekdays.", "Use buttons for selectable dates."],
      usage: ["Use as a low-level date picker foundation."],
      avoid: ["Do not use a static calendar for freeform date entry."],
    },
    name: "calendar",
    registryDependencies: [],
    title: "Calendar",
    valueExports: ["Calendar"],
  },
  {
    dependencies: [],
    description: "A native date input with Brilliant form styling.",
    exports: ["DateInputProps", "DateInput"],
    importPath: "@brilliant/ui/date-input",
    kind: "component",
    metadata: {
      purpose: "Collects a date using native platform controls.",
      slots: ["root"],
      accessibility: ["Uses native date input.", "Pair with a visible label."],
      usage: ["Use for straightforward date entry."],
      avoid: ["Do not use when users need date ranges or complex calendar constraints."],
    },
    name: "date-input",
    registryDependencies: [],
    title: "Date Input",
    valueExports: ["DateInput"],
  },
  {
    dependencies: [],
    description: "A command palette/listbox foundation.",
    exports: ["Command", "CommandInput", "CommandList", "CommandItem"],
    importPath: "@brilliant/ui/command",
    kind: "component",
    metadata: {
      purpose: "Builds command palettes and searchable action lists.",
      slots: ["root", "input", "list", "item"],
      accessibility: [
        "Uses listbox and option roles.",
        "Manage filtering and active state in app code.",
      ],
      usage: ["Use for command palettes, jump menus, and searchable actions."],
      avoid: ["Do not use without keyboard behavior for complex command centers."],
    },
    name: "command",
    registryDependencies: [],
    title: "Command",
    valueExports: ["Command", "CommandInput", "CommandList", "CommandItem"],
  },
] as const;
